### ISSUE TITLE
Error in Evaluation mode when using .npy files 

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#200]
--- Logging error ---
Traceback (most recent call last):
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/affinity-vae/run.py", line 664, in run
    run_pipeline(data)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/affinity-vae/run.py", line 714, in run_pipeline
    evaluate(
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/affinity-vae/avae/evaluate.py", line 212, in evaluate
    meta_df["image"] = meta_df["image"].apply(vis.merge)
  File "/bask/homes/h/hdjd5168/vjgo8416-ms-img-pc/marji/env_merge_codebase/lib/python3.10/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/bask/homes/h/hdjd5168/vjgo8416-ms-img-pc/marji/env_merge_codebase/lib/python3.10/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
  File "/bask/homes/h/hdjd5168/vjgo8416-ms-img-pc/marji/env_merge_codebase/lib/python3.10/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/affinity-vae/avae/vis.py", line 134, in merge
    i = im.split("&")
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by marjanfamili** [comment]
can we separate the restart feature and evaluation feature from the dynamic plots?

**Comment by crangelsmith** [comment]
Should be fixed in #208
