### ISSUE TITLE
Umap embedding fails due to uninitialised variable

### ISSUE THREAD

**Issue by jolaem** [alan-turing-institute/affinity-vae#261]
`class_list` variable is originally initialised under `VIS_SIM` condition so when `VIS_SIM` is set to `False`, umap will fail.

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/jola/mygit/affinity-vae/run.py", line 651, in run
    run_pipeline(data)
  File "/home/jola/mygit/affinity-vae/run.py", line 660, in run_pipeline
    train(
  File "/home/jola/mygit/affinity-vae/avae/train.py", line 607, in train
    xs, ys, classes_list, epoch=epoch, writer=writer
UnboundLocalError: local variable 'classes_list' referenced before assignment
```

**Comment by crangelsmith** [comment]
@jolaem are you working on a patch for this? otherwise, I'll fix it.
